# Generated by Django 5.1 on 2024-08-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(choices=[('q1_opt1', 'Question 1 Option 1'), ('q1_opt2', 'Question 1 Option 2'), ('q1_opt3', 'Question 1 Option 3')], default='q1_opt1', max_length=10)),
                ('question_2', models.CharField(choices=[('q2_opt1', 'Question 2 Option 1'), ('q2_opt2', 'Question 2 Option 2'), ('q2_opt3', 'Question 2 Option 3')], default='q2_opt1', max_length=10)),
            ],
        ),
    ]
