# Generated by Django 5.1 on 2024-08-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question_1',
            field=models.CharField(choices=[('q1_opt1', 'logical learning'), ('q1_opt2', 'creative learning'), ('q1_opt3', 'analitical learning')], default='q1_opt1', max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_2',
            field=models.CharField(choices=[('q2_opt1', 'written exams'), ('q2_opt2', 'tests'), ('q2_opt3', 'puzzeles')], default='q2_opt1', max_length=10),
        ),
    ]
