# Generated by Django 5.1 on 2024-08-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_survey_question_1_alter_survey_question_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question_1',
            new_name='optimum_learning',
        ),
    ]
